# Generated by Django 3.0.8 on 2020-07-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_address', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('technical_skillset', models.CharField(max_length=200)),
                ('work_experience', models.CharField(max_length=20)),
                ('employment_authorization', models.CharField(max_length=10)),
            ],
        ),
    ]
